'use client'
import { useState, useEffect } from 'react'
import AdminShell from '@/components/admin/AdminShell'

export default function AIDraftsPage() {
  const [drafts, setDrafts] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchDrafts = async () => {
      try {
        const res = await fetch('/api/newsroom/drafts')
        const data = await res.json()
        setDrafts(data.drafts || [])
        setLoading(false)
      } catch (err) {
        console.error('Failed to fetch drafts:', err)
        setLoading(false)
      }
    }

    fetchDrafts()
  }, [])

  if (loading) {
    return (
      <AdminShell>
        <div style={{ padding: '16px', textAlign: 'center', color: '#666' }}>Loading...</div>
      </AdminShell>
    )
  }

  return (
    <AdminShell>
      <div style={{ padding: '16px', maxWidth: '1200px', margin: '0 auto' }}>
        <div style={{ marginBottom: '24px' }}>
          <h1 style={{ fontSize: '24px', fontWeight: '700', marginBottom: '8px', fontFamily: 'Playfair Display, serif' }}>
            AI Drafts
          </h1>
          <p style={{ color: '#666', fontSize: '14px' }}>
            Articles generated by the AI newsroom pipeline
          </p>
        </div>

        {drafts.length === 0 ? (
          <div style={{ background: 'white', padding: '48px', borderRadius: '8px', border: '1px solid #e0e0e0', textAlign: 'center' }}>
            <div style={{ fontSize: '48px', marginBottom: '16px' }}>📥</div>
            <div style={{ fontSize: '16px', fontWeight: '600', marginBottom: '8px', color: '#333' }}>No drafts yet</div>
            <div style={{ color: '#666', fontSize: '14px' }}>
              Trigger the pipeline to generate AI drafts
            </div>
          </div>
        ) : (
          <div style={{ display: 'grid', gap: '12px' }}>
            {drafts.map((draft: any) => (
              <div key={draft.id} style={{ background: 'white', padding: '16px', borderRadius: '8px', border: '1px solid #e0e0e0' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '8px' }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: '16px', fontWeight: '600', marginBottom: '4px' }}>{draft.title}</div>
                    <div style={{ fontSize: '12px', color: '#666' }}>
                      {draft.sourceName} • {new Date(draft.createdAt).toLocaleString()}
                    </div>
                  </div>
                  <span style={{
                    fontSize: '11px',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    fontWeight: '600',
                    background: '#C62828',
                    color: 'white'
                  }}>
                    DRAFT_READY
                  </span>
                </div>
                <div style={{ display: 'flex', gap: '8px', marginTop: '12px' }}>
                  <button
                    onClick={() => window.location.href = `/admin/newsroom/review/${draft.id}`}
                    style={{
                      background: '#1976D2',
                      color: 'white',
                      border: 'none',
                      padding: '8px 16px',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontSize: '12px',
                      fontWeight: '600'
                    }}
                  >
                    Review
                  </button>
                  <button
                    onClick={() => window.location.href = `/admin/articles/${draft.id}`}
                    style={{
                      background: '#4CAF50',
                      color: 'white',
                      border: 'none',
                      padding: '8px 16px',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontSize: '12px',
                      fontWeight: '600'
                    }}
                  >
                    Edit
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </AdminShell>
  )
}
